add scripts/gvm-check and update bin/gvm script

diff --git a/bin/gvm b/bin/gvm
--- a/bin/gvm
+++ b/bin/gvm
@@ -1,15 +1,57 @@
 #!/usr/bin/env bash
 
 
-echo "GVM_DEBUG: $GVM_DEBUG"
+# echo "GVM_DEBUG: $GVM_DEBUG"
+# [ -n "$GVM_DEBUG" ] && {
+# #   set -x
+#     echo "=================== 111"
+# }
+
+# [ -z "$GVM_DEBUG" ] && {
+# #   set -x
+#     echo "=================== 222"
+# }
+
+
+# GVM_DEBUG="xxx"
+# echo "GVM_DEBUG: $GVM_DEBUG"
+# [ -n "$GVM_DEBUG" ] && {
+# #   set -x
+#     echo "+++++++++++++++++++ 111"
+# }
+
+
+# [ -z "$GVM_DEBUG" ] && {
+# #   set -x
+#     echo "+++++++++++++++++++ 222"
+# }
+
+
 [ -n "$GVM_DEBUG" ] && {
-#   set -x
-    echo "==================="
+  set -x
 }
 
-GVM_DEBUG="xxx"
-echo "GVM_DEBUG: $GVM_DEBUG"
-[ -n "$GVM_DEBUG" ] && {
-#   set -x
-    echo "+++++++++++++++++++"
-}
+echo "GVM_ROOT: $GVM_ROOT"
+if [ -z "$GVM_ROOT" ]; then
+	tput sgr0
+	tput setaf 1
+	echo 'ERROR: GVM_ROOT is not set! Please add the following line to your .bashrc or .profile
+
+	[[ -s "$HOME/.gvm/scripts/gvm" ]] && source "$HOME/.gvm/scripts/gvm"
+' >&2
+	tput sgr0
+	exit 1
+fi
+
+. "$GVM_ROOT/scripts/functions" || exit 1
+
+command=$1
+if [[ $command == "implode" ]]; then
+  gvm_implode
+	exit 0
+fi
+
+"$GVM_ROOT/scripts/gvm-check"
+if [[ "$?" != "0" ]]; then
+	display_fatal "Missing requirements."
+fi
